traceback (most recent call last):\n  File \"/shree/services.py\", line 59, in <module>\n    get_endpoints()\n  File \"/shree/services.py\", 
ine 18, in get_endpoints\n    output = popen(\"%s %s\" % (curl, sites[test][\"site\"])).readline().split(\",\")\n  File \"/usr/lib64/python3.4/os.py\", 
line 945, in popen\n    bufsize=buffering)\n  File \"/usr/lib64/python3.4/subprocess.py\", line 856, in __init__\n    restore_signals, start_new_session)\n 
restore_signals, start_new_session, preexec_fn)\nBlockingIOError: [Errno 11] Resource temporarily unavailable\n","status":1}}}
 File \"/usr/lib64/python3.4/subprocess.py\", line 1398, in _execute_child\n    
